### ISSUE TITLE
Couldn't we, just install the certificate manually under >Android 11 ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Mobile-IoT-Security-Lab/HideDroid#2]
Hi there,
I've discovered your application and project from IzzySoft repo. Really great path of approach to improve user privacy.
Using a CalyxOS rom which is Android 11 based at the moment, I've did noticed the described issue in the project README.md. The security/privacy restriction of allowing applications to automatically install CA certificates.
However, as a non-developer android enthusiast _(Meaning that i actually don't know what I'm talking about technically speaking)_, I've been wondering.
* Could the application potentially request to be given adb developers or root rights as a workaround ? This does indeed make the process of setting it up more complex and potentially dangerous on a security stand-point, but such as installing a CA certificate to re-route application network traffic *(Even if your code is entirely open)*.
* I believe the reason you haven't thought of suggesting to add the CA certificate manually, is because it is actually generated on activation by the application, and so, is unique to your device. In the case that the application detect a problematic Android version, couldn't be saved in the accessible HideDroid folder in the user filespace folder ? That way, the user could install the generated CA certificate manually, the way like ad-blocking software like Blokada, offers for a much full-proof and rootless network advertisement filtering.

**Comment by Dado1513** [comment]
Hi @PoorPocketsMcNewHold,

If you have root permission on your Android device, HideDroid works perfectly without any problems (CA certificates are generated for each application).

However, if you don't have root permission, we are working on a newer version of HideDroid. You can watch it on the branch [test-android-11-support](https://github.com/Mobile-IoT-Security-Lab/HideDroid/issues/2).
