### ISSUE TITLE
App doesn't generate CA certificate

### ISSUE THREAD

**Issue by dic1911** [Mobile-IoT-Security-Lab/HideDroid#6]
After the pop-up told me to install CA certificate in "Settings", there's no CA cert generated in "HideDroid" folder, and there seem no related stuff in logcat either.

edit: I'm on LineageOS 18.1 (Pixel 4a 5G)

**Comment by Tomoms** [comment]
If you installed the app from F-Droid, you're most likely using an old version (1.1.2). Upgrade to the last one (1.2) by downloading it from Github Releases and the certificate will be generated.

**Comment by shom13** [comment]
Just downloaded version 1.2 it still starts saying not ready install cert from sd card

**Comment by shom13** [comment]
Redownloaded the app and i was able to get it to work
